# Generated by Django 3.2 on 2021-05-15 01:38

import citas.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=225)),
                ('apellido', models.CharField(max_length=225)),
                ('especialidad', models.CharField(choices=[('Odontologo', 'Odontologo'), ('Odontologa', 'Odontologa')], default='available', max_length=100)),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='available', max_length=30)),
                ('direccion', models.TextField(blank=True, max_length=225)),
                ('celular', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=225)),
                ('apellido', models.CharField(max_length=225)),
                ('direccion', models.TextField(max_length=225)),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='available', max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=225)),
                ('paciente', models.ForeignKey(default='available', on_delete=django.db.models.deletion.CASCADE, to='citas.paciente')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=10, verbose_name='Celular')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('cedula', models.CharField(max_length=10, verbose_name='Cedula')),
                ('foto', models.ImageField(upload_to=citas.models.url_perfil, verbose_name='Foto')),
                ('usuario', models.OneToOneField(default='available', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.CharField(choices=[('8:00/8:30 AM', '8:00/8:30 AM'), ('8:30/9:00 AM', '8:30/9:00 AM'), ('9:00/9:30 AM', '9:00/9:30 AM'), ('9:30/10:00 AM', '9:30/10:00 AM'), ('10:00/10:30 AM', '10:00/10:30 AM'), ('10:30/11:00 AM', '10:30/11:00 AM'), ('11:00/11:30 AM', '11:00/11:30 AM'), ('11:30/12:00 AM', '11:30/12:00 AM'), ('13:00/13:30 PM', '13:00/13:30 PA'), ('13:30/14:00 PM', '13:30/14:00 PM'), ('14:00/14:30 PM', '14:00/14:30 PM'), ('14:30/15:00 PM', '14:30/15:00 PM'), ('15:00/15:30 PM', '15:00/15:30 PM'), ('15:30/16:00 PM', '15:30/16:00 PM'), ('16:00/16:30 PM', '14:00/16:30 PM'), ('16:30/17:00 PM', '16:30/17:00 PM')], default='available', max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=225)),
                ('doctor', models.ForeignKey(default='available', on_delete=django.db.models.deletion.CASCADE, to='citas.doctor')),
                ('paciente', models.ForeignKey(default='available', on_delete=django.db.models.deletion.CASCADE, to='citas.paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'doctor'],
            },
        ),
    ]
