# Generated by Django 3.2 on 2021-08-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['doctor', 'fecha'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.CharField(choices=[('8:00 am/8:30 am', '8:00 am/8:30 am'), ('8:30 am/9:00 am', '8:30 am/9:00 am'), ('9:00 am/9:30 am', '9:00 am/9:30 am'), ('9:30 am/10:00 am', '9:30 am/10:00 am'), ('10:00 am/10:30 am', '10:00 am/10:30 am'), ('10:30 am/11:00 am', '10:30 am/11:00 am'), ('11:00 am/11:30 am', '11:00 am/11:30 am'), ('11:30 am/12:00 pm', '11:30 am/12:00 pm'), ('13:00 pm/13:30 pm', '13:00 pm/13:30 pm'), ('13:30 pm/14:00 pm', '13:30 pm/14:00 pm'), ('14:00 pm/14:30 pm', '14:00 pm/14:30 pm'), ('14:30 pm/15:00 pm', '14:30 pm/:15:00 pm'), ('15:00 pm/15:30 pm', '15:00 pm/15:30 pm'), ('15:30 pm/16:00 pm', '15:30 pm/16:00 pm'), ('16:00 pm/16:30 pm', '16:00 pm/16:30 pm'), ('16:30 am/17:00 am', '16:30 am/17:00 am')], default='available', max_length=60),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='direccion',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='observacion',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
