# Generated by Django 3.2 on 2021-07-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='observacion',
            field=models.TextField(blank=True, max_length=225),
        ),
    ]
