# Generated by Django 3.2 on 2021-05-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='Edad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='estado',
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.CharField(choices=[('8:00/8:30 AM', '8:00/8:30 AM'), ('8:30/9:00 AM', '8:30/9:00 AM'), ('9:00/9:30 AM', '9:00/9:30 AM'), ('9:30/10:00 AM', '9:30/10:00 AM'), ('10:00/10:30 AM', '10:00/10:30 AM'), ('10:30/11:00 AM', '10:30/11:00 AM'), ('11:00/11:30 AM', '11:00/11:30 AM'), ('11:30/12:00 AM', '11:30/12:00 AM'), ('13:00/13:30 PM', '13:00/13:30 PA'), ('13:30/14:00 PM', '13:30/14:00 PM'), ('14:00/14:30 PM', '14:00/14:30 PM'), ('14:30/15:00 PM', '14:30/15:00 PM'), ('15:00/15:30 PM', '15:00/15:30 PM'), ('15:30/16:00 PM', '15:30/16:00 PM'), ('16:00/16:30 PM', '14:00/16:30 PM'), ('16:30/17:00 PM', '16:30/17:00 PM')], default='available', max_length=50, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sexo',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha',
            field=models.DateField(),
        ),
    ]
