# Generated by Django 3.2 on 2021-05-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['doctor'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
    ]
