# Generated by Django 3.2 on 2021-05-30 19:15

import citas.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=citas.models.url_perfil, verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
