# Generated by Django 3.2 on 2021-08-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_paciente_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='direccion',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='observacion',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='observacion',
            field=models.TextField(max_length=225),
        ),
    ]
