# Generated by Django 3.2 on 2021-06-01 13:13

import citas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default=None, upload_to=citas.models.url_perfil),
        ),
    ]
