# Generated by Django 3.2 on 2021-05-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_auto_20210502_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.CharField(choices=[('8:00/8:30 AM', '8:00/8:30 AM'), ('8:30/9:00 AM', '8:30/9:00 AM'), ('9:00/9:30 AM', '9:00/9:30 AM'), ('9:30/10:00 AM', '9:30/10:00 AM'), ('10:00/10:30 AM', '10:00/10:30 AM'), ('10:30/11:00 AM', '10:30/11:00 AM'), ('11:00/11:30 AM', '11:00/11:30 AM'), ('11:30/12:00 AM', '11:30/12:00 AM'), ('13:00/13:30 PM', '13:00/13:30 PA'), ('13:30/14:00 PM', '13:30/14:00 PM'), ('14:00/14:30 PM', '14:00/14:30 PM'), ('14:30/15:00 PM', '14:30/15:00 PM'), ('15:00/15:30 PM', '15:00/15:30 PM'), ('15:30/16:00 PM', '15:30/16:00 PM'), ('16:00/16:30 PM', '14:00/16:30 PM'), ('16:30/17:00 PM', '16:30/17:00 PM')], default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='available', max_length=30),
        ),
    ]
