# Generated by Django 3.2 on 2021-07-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='direccion',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='observacion',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='observacion',
            field=models.TextField(max_length=225),
        ),
    ]
