# Generated by Django 3.2 on 2021-08-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_auto_20210731_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.CharField(choices=[('8:00 am/8:30 am', '8:00 am/8:30 am'), ('8:30 am/9:00 am', '8:30 am/9:00 am'), ('9:00 am/9:30 am', '9:00 am/9:30 am'), ('9:30 am/10:00 am', '9:30 am/10:00 am'), ('10:00 am/10:30 am', '10:00 am/10:30 am'), ('10:30 am/11:00 am', '10:30 am/11:00 am'), ('11:00 am/11:30 am', '11:00 am/11:30 am'), ('11:30 am/12:00 pm', '11:30 am/12:00 pm'), ('13:00 pm/13:30 pm', '13:00 pm/13:30 pm'), ('13:30 pm/14:00 pm', '13:30 pm/14:00 pm'), ('14:00 pm/14:30 pm', '14:00 pm/14:30 pm'), ('14:30 pm/15:00 pm', '14:30 pm/:15:00 pm'), ('15:00 pm/15:30 pm', '15:00 pm/15:30 pm'), ('15:30 pm/16:00 pm', '15:30 pm/16:00 pm'), ('16:00 pm/16:30 pm', '16:00 pm/16:30 pm'), ('16:30 am/17:00 am', '16:30 am/17:00 am')], default='available', max_length=60),
        ),
    ]
