# Generated by Django 3.2 on 2021-05-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_auto_20210504_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='direccion',
            field=models.TextField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(max_length=225),
        ),
    ]
