# Generated by Django 3.2 on 2021-05-23 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='correo',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
