# Generated by Django 3.2 on 2021-05-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_perfil_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(choices=[('Odontologo', 'Odontologo'), ('Odontologa', 'Odontologa')], default='available', max_length=60),
        ),
    ]
